# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore --ignore-failed-sources

    - name: Build
      run: |
        for proj in $(find . -name '*.csproj'); do
          if [[ $proj != *".sqlproj" ]]; then
            dotnet build "$proj" --configuration Release --no-restore
          fi
        done
